
[tool.poetry]
name = "simple-project"
version = "0"
description = "packaging service"
authors = ["Max Chalitsios <mchalitsios@eogresources.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
